# Generated by Django 5.0.14 on 2025-05-22 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0002_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100)),
                ('jersey', models.IntegerField(blank=True, null=True)),
                ('class_year', models.CharField(blank=True, max_length=20, null=True)),
                ('player_url', models.URLField(blank=True, max_length=300)),
                ('player_stats_url', models.URLField(blank=True, max_length=300)),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='draft.position')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='draft.collegeteam')),
            ],
        ),
    ]
