# Generated by Django 5.0.14 on 2025-05-22 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0003_player'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='adp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
