# Generated by Django 5.0.14 on 2025-05-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0004_player_adp'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='alternate_names',
            field=models.TextField(blank=True, null=True),
        ),
    ]
