# Generated by Django 5.0.14 on 2025-05-24 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draft', '0005_player_alternate_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='adp',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
